### ISSUE TITLE
Ingress error

### ISSUE THREAD

**Issue by vivekhimalayas** [vdaas/vald#1045]
helm install vald vald/vald --values example/helm/values-scylla.yaml

Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"

I tried to set the value of usev1beta1 to true there in the file - ./charts/vald/values.yaml but still getting the error.

Can someone please help?

### Environment:

- Go Version: 1.16
- Docker Version: 19.03.8
- Kubernetes Version: 1.18.2
- NGT Version: 1.12.3

**Comment by rinx** [comment]
Did you solved the problem?
