### ISSUE TITLE
Option to delete indexes

### ISSUE THREAD

**Issue by vivekhimalayas** [vdaas/vald#1050]
Is there any way I can delete indexes. I created some for testing. I am using scyalla db. Are the indexes stored in db?

**Comment by kpango** [comment]
@vivekhimalayas Thanks for the question.
we also provide [remove API](https://github.com/vdaas/vald/blob/master/apis/proto/v1/vald/remove.proto#L38-L53).
For example, in the case of the [Python Client](https://github.com/vdaas/vald-client-python), you can use delete gRPC stub and execute the remove API.

**Comment by vivekhimalayas** [comment]
Thanks for the quick response.

**Comment by rinx** [comment]
@vivekhimalayas There's the Vald community Slack (vald-community.slack.com).
You can join from here and ask anything to us freely.
https://join.slack.com/t/vald-community/shared_invite/zt-db2ky9o4-R_9p2sVp8xRwztVa8gfnPA

**Comment by vankichi** [comment]
@vivekhimalayas
Thanks for the question.
I'd like to announce to you that the document of `Get-Started` is just updated.
We added the content of the remove index section for each tutorial (Vald on k8s and standalone Vald).
Please check [here](https://vald.vdaas.org/docs/tutorial/get-started/) when you are free.
