### ISSUE TITLE
When you deploy vald helm chart with initialer enable the job will be fail

### ISSUE THREAD

**Issue by jmvizcainoio** [vdaas/vald#1184]
### Describe the bug:

The schema that will create the initializer job seems not corret

```
kubectl logs -f mysql-init-gprsh
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1072 (42000) at line 6: Key column 'meta' doesn't exist in table
```

### To Reproduce:

Deploy helm chart vald and enable initializer 

The job try to execute 

```
CREATE TABLE IF NOT EXISTS `vald`.`backup_vector` (
    ->         `uuid` VARCHAR(255) NOT NULL,
    ->         `vector` BLOB NOT NULL,
    ->         `id` int NOT NULL AUTO_INCREMENT,
    ->         PRIMARY KEY (`uuid`),
    ->         UNIQUE INDEX `id_unique` (`id` ASC),
    ->         UNIQUE INDEX `meta_unique` (`meta` ASC)
    ->     )
    ->     ENGINE = InnoDB;
```

but the `meta` column doesn't exist and the index creation fail. 

### Environment:

- Go Version: 1.15.6
- Docker Version: 19.03.8
- Kubernetes Version: 1.19.2
- NGT Version: 1.12.3

**Comment by rinx** [comment]
@jmvizcainoio Thanks for reporting.

I've just created a PR that fixes this issue. #1186 

As a temporary workaround, please overwrite your deployed configmap by executing this command.
```
kubectl apply -f https://raw.githubusercontent.com/vdaas/vald/bugfix/helm-chart/fix-mysql-cassandra-schema-definitions/k8s/jobs/db/initialize/mysql/configmap.yaml
```

**Comment by kpango** [comment]
@jmvizcainoio we relased new Vald version v1.1.0 now including #1186.
so I'll close this issue, thanks for reporting!
