### ISSUE TITLE
Error definition should not put in error package

### ISSUE THREAD

**Issue by kevindiu** [vdaas/vald#120]
Now in vald, all error definition is defined in `internal/errors` package. 
But I don't think it is a good practice in golang, as the error should belongs to meaningful package instead of misleading `errors` package. Even in golang implementation it is definied under the corresponding package, for example:  
https://golang.org/src/net/http/server.go :Line974

**Comment by kpango** [comment]
I understand your opinion and I also understand go's default package Err variable,
but I think vald's centralized error is effective for maitain each error in monorepo-microservices,
In my opinion we should change cureent structure but we have to maintain error codes centric so how about write type alias to each package

**Comment by kevindiu** [comment]
Type alias makes the code difficult to maintain. 🤔 I am just thinking if we define all the error in 1 package then user needs to think which definition they should use as some of them may have similar definition.
