### ISSUE TITLE
Example does not up, IB and index-manager is CrashLoopBackOff

### ISSUE THREAD

**Issue by yoshimur** [vdaas/vald#1277]
### Describe the bug:
Using clean installed Ubuntu 20.04LTS or AlmaLinux
Run steps in Get Started with using Kind.
After helm install command, Kubectl get pods show followin.

> kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
vald-agent-ngt-0                      1/1     Running            0          5m24s
vald-agent-ngt-1                      1/1     Running            0          5m24s
vald-agent-ngt-2                      1/1     Running            0          5m24s
vald-agent-ngt-3                      1/1     Running            0          5m24s
vald-agent-ngt-4                      1/1     Running            0          5m24s
vald-discoverer-64b77c68bf-djvj4      1/1     Running            0          5m24s
vald-lb-gateway-9f85d5755-6djcw       0/1     CrashLoopBackOff   6          5m9s
vald-lb-gateway-9f85d5755-vwxbk       0/1     CrashLoopBackOff   6          5m9s
vald-lb-gateway-9f85d5755-znpq4       0/1     CrashLoopBackOff   6          5m24s
vald-manager-index-5b99bf897c-5zsjq   0/1     CrashLoopBackOff   6          5m24s

valid-lb and valid manager-index does not become READY.
Followind FATAL Message is shown using kubectl logs command.

> 2021-06-07 00:31:39	[FATAL]:	failed to start daemon: addr vald-agent-ngt.default.svc.cluster.local ip couldn't discover: operation was canceled 

### To Reproduce:
I try clean installed Ubuntu 20.04LTS and AlmaLinux, It is reproduced.
In AlmaLinux case, I make Kubenetes CLuster, but it is same error.

### Expected behavior:

vald-lb-gateway and vald-manager-index will become READY

### Environment:

- Go Version: 1.15.7
- Docker Version: 20.10.7
- Kind Version: v0.11.0

**Comment by vankichi** [comment]
Hi, @yoshimur !
Thx for trying `GetStarted`.

Could you show us the machine spec which you're using now, and the output of `kubectl describe pod <CrashLooped Pods>?

**Comment by yoshimur** [comment]
I'm using VMware Workstation Pro with AMD 5950X + 64GB Memory.
Virtual Machine Spec is follow
  vCPUs : 8core
 Memory: 16MB
OS is AlmaLinux

And one crashed pod(s describe output is follow:
$ kubectl get pods
NAME                                  READY   STATUS             RESTARTS   AGE
vald-agent-ngt-0                      1/1     Running            0          4m22s
vald-agent-ngt-1                      1/1     Running            0          4m22s
vald-agent-ngt-2                      1/1     Running            0          4m22s
vald-agent-ngt-3                      1/1     Running            0          4m22s
vald-agent-ngt-4                      1/1     Running            0          4m22s
vald-discoverer-64b77c68bf-cp5k9      1/1     Running            0          4m22s
vald-lb-gateway-9f85d5755-2v8ml       0/1     CrashLoopBackOff   5          4m22s
vald-lb-gateway-9f85d5755-pks45       0/1     CrashLoopBackOff   5          4m7s
vald-lb-gateway-9f85d5755-sjtcq       0/1     Running            6          4m7s
vald-manager-index-5b99bf897c-xwsmn   0/1     CrashLoopBackOff   5          4m22s
$ kubectl describe pod vald-lb-gateway-9f85d5755-2v8ml
Name:                 vald-lb-gateway-9f85d5755-2v8ml
Namespace:            default
Priority:             1000000
Priority Class Name:  default-vald-lb-gateway-priority
Node:                 kind-control-plane/172.18.0.2
Start Time:           Mon, 07 Jun 2021 13:32:51 +0900
Labels:               app=vald-lb-gateway
                      app.kubernetes.io/component=gateway-lb
                      app.kubernetes.io/instance=vald
                      app.kubernetes.io/name=vald
                      pod-template-hash=9f85d5755
Annotations:          checksum/configmap: cfb93c1da1ddecf223e7a69027a89d1137aaafe52b9dc8edb338f7e0bf25cd57
Status:               Running
IP:                   10.244.0.11
IPs:
  IP:           10.244.0.11
Controlled By:  ReplicaSet/vald-lb-gateway-9f85d5755
Init Containers:
  wait-for-discoverer:
    Container ID:  containerd://4c94910ef9f95e9f36a61802f77297260f4455464de9be1148ff4ffae0b7085c
    Image:         busybox
    Image ID:      docker.io/library/busybox@sha256:b5fc1d7b2e4ea86a06b0cf88de915a2c43a99a00b6b3c0af731e5f4c07ae8eff
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -e
      -c
      until [ "$(wget --server-response --spider --quiet http://vald-discoverer.default.svc.cluster.local:3001/readiness 2>&1 | awk 'NR==1{print $2}')" == "200" ]; do
        echo "waiting for discoverer to be ready..."
        sleep 2;
      done
      
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 07 Jun 2021 13:33:15 +0900
      Finished:     Mon, 07 Jun 2021 13:33:45 +0900
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-dr5mb (ro)
  wait-for-agent:
    Container ID:  containerd://9c3f297c9eb960ab1b558007d2a462999130be007af66296ed934120f208aa85
    Image:         busybox
    Image ID:      docker.io/library/busybox@sha256:b5fc1d7b2e4ea86a06b0cf88de915a2c43a99a00b6b3c0af731e5f4c07ae8eff
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -e
      -c
      until [ "$(wget --server-response --spider --quiet http://vald-agent-ngt.default.svc.cluster.local:3001/readiness 2>&1 | awk 'NR==1{print $2}')" == "200" ]; do
        echo "waiting for agent to be ready..."
        sleep 2;
      done
      
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 07 Jun 2021 13:33:47 +0900
      Finished:     Mon, 07 Jun 2021 13:33:47 +0900
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-dr5mb (ro)
Containers:
  vald-lb-gateway:
    Container ID:   containerd://51e00f2cb508933b92e8ee3a934424ff9091434c8fabb13c5833716b517c3d4a
    Image:          vdaas/vald-lb-gateway:latest
    Image ID:       docker.io/vdaas/vald-lb-gateway@sha256:58332183880dc482a975e0353ae2e4726e1d18f7d341352f68464f893b4832eb
    Ports:          3000/TCP, 3001/TCP, 8081/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 07 Jun 2021 13:35:58 +0900
      Finished:     Mon, 07 Jun 2021 13:36:06 +0900
    Ready:          False
    Restart Count:  5
    Limits:
      cpu:     2
      memory:  700Mi
    Requests:
      cpu:      150m
      memory:   150Mi
    Liveness:   http-get http://:liveness/liveness delay=5s timeout=2s period=3s #success=1 #failure=2
    Readiness:  http-get http://:readiness/readiness delay=10s timeout=2s period=3s #success=1 #failure=2
    Environment:
      MY_POD_NAMESPACE:  default (v1:metadata.namespace)
    Mounts:
      /etc/server/ from vald-lb-gateway-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-dr5mb (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  vald-lb-gateway-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      vald-lb-gateway-config
    Optional:  false
  kube-api-access-dr5mb:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  4m38s                  default-scheduler  Successfully assigned default/vald-lb-gateway-9f85d5755-2v8ml to kind-control-plane
  Normal   Pulling    4m36s                  kubelet            Pulling image "busybox"
  Normal   Pulled     4m14s                  kubelet            Successfully pulled image "busybox" in 22.145350442s
  Normal   Created    4m14s                  kubelet            Created container wait-for-discoverer
  Normal   Started    4m14s                  kubelet            Started container wait-for-discoverer
  Normal   Pulling    3m43s                  kubelet            Pulling image "busybox"
  Normal   Pulled     3m42s                  kubelet            Successfully pulled image "busybox" in 1.635730383s
  Normal   Created    3m42s                  kubelet            Created container wait-for-agent
  Normal   Started    3m42s                  kubelet            Started container wait-for-agent
  Normal   Pulled     3m37s                  kubelet            Successfully pulled image "vdaas/vald-lb-gateway:latest" in 4.719999338s
  Normal   Created    3m24s (x2 over 3m37s)  kubelet            Created container vald-lb-gateway
  Normal   Started    3m24s (x2 over 3m37s)  kubelet            Started container vald-lb-gateway
  Normal   Pulled     3m24s                  kubelet            Successfully pulled image "vdaas/vald-lb-gateway:latest" in 5.003414427s
  Normal   Pulling    3m14s (x3 over 3m41s)  kubelet            Pulling image "vdaas/vald-lb-gateway:latest"
  Warning  Unhealthy  3m14s (x4 over 3m32s)  kubelet            Liveness probe failed: Get "http://10.244.0.11:3000/liveness": dial tcp 10.244.0.11:3000: connect: connection refused
  Normal   Killing    3m14s (x2 over 3m29s)  kubelet            Container vald-lb-gateway failed liveness probe, will be restarted
  Warning  Unhealthy  3m14s (x2 over 3m26s)  kubelet            Readiness probe failed: Get "http://10.244.0.11:3001/readiness": dial tcp 10.244.0.11:3001: connect: connection refused

Best regards.

**Comment by vankichi** [comment]
@yoshimur 
thanks for show us the your detail condition. I think resource is fine.

> Warning Unhealthy 3m14s (x4 over 3m32s) kubelet Liveness probe failed: Get "http://10.244.0.11:3000/liveness": dial tcp 10.244.0.11:3000: connect: connection refused
> Warning Unhealthy 3m14s (x2 over 3m26s) kubelet Readiness probe failed: Get "http://10.244.0.11:3001/readiness": dial tcp 10.244.0.11:3001: connect: connection refused

From these log, it looks creating/starting container failed due to short initial duration.

Please set `defaults.server_config.healths.liveness.livenessProbe.initialDelaySeconds` and `defaults.server_config.healths.readiness.readinessProbe.initialDelaySeconds` to be long time (e.g. 30, 60), and try again.
(default value is 10).

thanks.

**Comment by yoshimur** [comment]
I try to chenged initialDelaySeconds to 60 second
But status is not changed, LB and Manger Index was still CrashLoopBackOff

and, Memory Size is 16GB.

Best Regards.

**Comment by vankichi** [comment]
@yoshimur 
The output of `kubectl describe pod ...` is same yet?
If yes, please set to be more long time.

thanks.

**Comment by yoshimur** [comment]
describe is follow,. It seems same.

kubectl describe pod vald-lb-gateway-9f85d5755-7qrkm
Name:                 vald-lb-gateway-9f85d5755-7qrkm
Namespace:            default
Priority:             1000000
Priority Class Name:  default-vald-lb-gateway-priority
Node:                 kind-control-plane/172.18.0.2
Start Time:           Mon, 07 Jun 2021 15:06:57 +0900
Labels:               app=vald-lb-gateway
                      app.kubernetes.io/component=gateway-lb
                      app.kubernetes.io/instance=vald
                      app.kubernetes.io/name=vald
                      pod-template-hash=9f85d5755
Annotations:          checksum/configmap: cfb93c1da1ddecf223e7a69027a89d1137aaafe52b9dc8edb338f7e0bf25cd57
Status:               Running
IP:                   10.244.0.14
IPs:
  IP:           10.244.0.14
Controlled By:  ReplicaSet/vald-lb-gateway-9f85d5755
Init Containers:
  wait-for-discoverer:
    Container ID:  containerd://393a9f5e54e6634300b09884c088ba39c58e95caeb85cbc1c39cc4251be3b71c
    Image:         busybox
    Image ID:      docker.io/library/busybox@sha256:b5fc1d7b2e4ea86a06b0cf88de915a2c43a99a00b6b3c0af731e5f4c07ae8eff
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -e
      -c
      until [ "$(wget --server-response --spider --quiet http://vald-discoverer.default.svc.cluster.local:3001/readiness 2>&1 | awk 'NR==1{print $2}')" == "200" ]; do
        echo "waiting for discoverer to be ready..."
        sleep 2;
      done
      
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 07 Jun 2021 15:07:09 +0900
      Finished:     Mon, 07 Jun 2021 15:07:23 +0900
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-l5fb5 (ro)
  wait-for-agent:
    Container ID:  containerd://477b80b6e3f870f8e25b0956dbfbf070415d09b03f2a9f53ca2249ba433516de
    Image:         busybox
    Image ID:      docker.io/library/busybox@sha256:b5fc1d7b2e4ea86a06b0cf88de915a2c43a99a00b6b3c0af731e5f4c07ae8eff
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -e
      -c
      until [ "$(wget --server-response --spider --quiet http://vald-agent-ngt.default.svc.cluster.local:3001/readiness 2>&1 | awk 'NR==1{print $2}')" == "200" ]; do
        echo "waiting for agent to be ready..."
        sleep 2;
      done
      
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 07 Jun 2021 15:07:34 +0900
      Finished:     Mon, 07 Jun 2021 15:07:34 +0900
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-l5fb5 (ro)
Containers:
  vald-lb-gateway:
    Container ID:   containerd://9d214d43bad8f6e2086b4df61dd156c81e449e127f48766e8ff17f74d10d8c82
    Image:          vdaas/vald-lb-gateway:latest
    Image ID:       docker.io/vdaas/vald-lb-gateway@sha256:58332183880dc482a975e0353ae2e4726e1d18f7d341352f68464f893b4832eb
    Ports:          3000/TCP, 3001/TCP, 8081/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 07 Jun 2021 15:14:09 +0900
      Finished:     Mon, 07 Jun 2021 15:14:18 +0900
    Ready:          False
    Restart Count:  7
    Limits:
      cpu:     2
      memory:  700Mi
    Requests:
      cpu:      150m
      memory:   150Mi
    Liveness:   http-get http://:liveness/liveness delay=5s timeout=2s period=3s #success=1 #failure=2
    Readiness:  http-get http://:readiness/readiness delay=10s timeout=2s period=3s #success=1 #failure=2
    Environment:
      MY_POD_NAMESPACE:  default (v1:metadata.namespace)
    Mounts:
      /etc/server/ from vald-lb-gateway-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-l5fb5 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  vald-lb-gateway-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      vald-lb-gateway-config
    Optional:  false
  kube-api-access-l5fb5:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Pulling    8m30s                   kubelet            Pulling image "busybox"
  Normal   Scheduled  8m30s                   default-scheduler  Successfully assigned default/vald-lb-gateway-9f85d5755-7qrkm to kind-control-plane
  Normal   Pulled     8m18s                   kubelet            Successfully pulled image "busybox" in 12.111052348s
  Normal   Started    8m18s                   kubelet            Started container wait-for-discoverer
  Normal   Created    8m18s                   kubelet            Created container wait-for-discoverer
  Normal   Pulling    8m3s                    kubelet            Pulling image "busybox"
  Normal   Pulled     7m53s                   kubelet            Successfully pulled image "busybox" in 10.024141541s
  Normal   Created    7m53s                   kubelet            Created container wait-for-agent
  Normal   Started    7m53s                   kubelet            Started container wait-for-agent
  Normal   Pulled     7m47s                   kubelet            Successfully pulled image "vdaas/vald-lb-gateway:latest" in 5.169572595s
  Warning  Unhealthy  7m36s                   kubelet            Readiness probe failed: Get "http://10.244.0.14:3001/readiness": dial tcp 10.244.0.14:3001: connect: connection refused
  Normal   Created    7m36s (x2 over 7m47s)   kubelet            Created container vald-lb-gateway
  Normal   Started    7m36s (x2 over 7m47s)   kubelet            Started container vald-lb-gateway
  Normal   Pulled     7m36s                   kubelet            Successfully pulled image "vdaas/vald-lb-gateway:latest" in 3.341222061s
  Normal   Pulling    7m27s (x3 over 7m52s)   kubelet            Pulling image "vdaas/vald-lb-gateway:latest"
  Normal   Killing    7m27s (x2 over 7m39s)   kubelet            Container vald-lb-gateway failed liveness probe, will be restarted
  Warning  Unhealthy  7m27s (x4 over 7m42s)   kubelet            Liveness probe failed: Get "http://10.244.0.14:3000/liveness": dial tcp 10.244.0.14:3000: connect: connection refused
  Normal   Pulled     7m26s                   kubelet            Successfully pulled image "vdaas/vald-lb-gateway:latest" in 1.617284769s
  Warning  BackOff    3m28s (x19 over 7m18s)  kubelet            Back-off restarting failed container


And One question. 
The middle of this log, following line is found.

>     Ports:          3000/TCP, 3001/TCP, 8081/TCP
>     Host Ports:     0/TCP, 0/TCP, 0/TCP

Is this correct values?

Best Regards.

**Comment by kpango** [comment]
It seems that the probe settings have not been updated and the delays are set to 5 and 10 seconds.
Please try to update the probe settings.

> Liveness: http-get http://:liveness/liveness delay=5s timeout=2s period=3s #success=1 #failure=2
> Readiness: http-get http://:readiness/readiness delay=10s timeout=2s period=3s #success=1 #failure=2


We have not tested it on VMWare workstation pro, but we have confirmed that it works on k3d on MacOS, k3d&kind on ArchLinux, and Kubernetes Cluster on OpenStack cluster.
Could you please try to deploy on AlmaLinux without VM if possible?

These errors can be caused by internal errors, but in most cases they are caused by Context Cancel, which in Vald is often caused by SIGTERM.

> operation was canceled

Depending on the system specification, SIGTERM may be sent to the process without the probe terminating normally due to the delay at startup.
Therefore, if the delay is caused by the environment of the user executing the Probe, it is necessary to set the initialDelaySeconds longer. If the delay is caused by the environment of the user executing the Probe, it is necessary to set the initialDelaySeconds longer.

**Comment by yoshimur** [comment]
Thank you.
I try to change settings again, and check to use edited charts. 
And then, It work fine.

Best regards.

**Comment by kpango** [comment]
@yoshimur Thanks for the Issue report.
It might be that DefaultValue of initailDelay requires too many specs for most of the users' environment, and we will take this into consideration and change the default value used in GetStarted to a longer one.
