### ISSUE TITLE
Feature / architecture diagram

### ISSUE THREAD

**Issue by DmitryKey** [vdaas/vald#1456]
Hey Vald Team! 

I’m working on a Tech Radar-like blog post giving a high-level overview of vector search databases and platforms.
Right now I’m hunting for an architecture diagram, something that can both include a system level overview (engineering components) as well as feature level — for instance what algorithms exist in vector retrieval / ranking as well if there is a way to plug-in own algorithms. Found this system level diagram: https://vald.vdaas.org/docs/overview/architecture/
Do you have a similar one for supported features?

Btw, I've tried to join your Slack, but it didn't let me in. Is it open for public?

**Comment by vankichi** [comment]
Hi @DmitryKey !
Thanks for contact to us.
I'm vankichi, one of the Vald contributors.
At first, I answered your question.
We're sorry, we're providing only the architecture overview document you showed.
We're thinking to publish new documents which are spotting each component's feature.
( But, the publish date is not decided yet.)

we're also publishing the data flow document: https://vald.vdaas.org/docs/overview/data-flow/
Is this useful?

> Btw, I've tried to join your Slack, but it didn't let me in. Is it open for public?

Maybe it is public.
If you cannot join yet, I'll check with the administrator and let you know.

Btw, I'm very interested in what you do!

Thanks!

**Comment by DmitryKey** [comment]
Hi @vankichi !
Thanks for your answers and pointing me to the data flow diagrams -- they look interesting. I will think about these.

For feature diagram -- if you could update this ticket whenever it is ready, then I could modify my blog post.
Or via Slack, once I get in there -- and thanks if you could ask about it.

Btw, one other question I had, which is relevant for the blog -- do you have a cloud offering for Vald? Or do I need to host it myself?

> Btw, I'm very interested in what you do!
Thank you! If this is of interest to you, you can follow / read my blogs here: https://dmitry-kan.medium.com/
You are doing quite an interesting work with Vald, I'm impressed with your scalable algorithm and architecture!

**Comment by DmitryKey** [comment]
Hi @vankichi 
The blog has been published now: https://dmitry-kan.medium.com/milvus-pinecone-vespa-weaviate-vald-gsi-what-unites-these-buzz-words-and-what-makes-each-9c65a3bd0696

If you have some clarifications to add -- let me know!

**Comment by vankichi** [comment]
Hi @DmitryKey .

> Btw, one other question I had, which is relevant for the blog -- do you have a cloud offering for Vald? Or do I need to host it myself?

Vald can be used by self hosted.

Thanks for sharing your post!
It's very helpful for our future roadmap :)

When we publish the new documents, let you know!

**Comment by vankichi** [comment]
Hi @DmitryKey !

The architecture image in your post seems large.
could you please use the below image?
It will be fit in medium blog page.

![vald_basic_architecture](https://user-images.githubusercontent.com/13959763/135806067-b5c7953f-0d4c-451a-8aca-5804a7c1725f.png)

**Comment by DmitryKey** [comment]
hi @vankichi !
Thanks for the updated diagram, I have now replaced it on the blog post. It fits nicely now :)
Also, for your information this blog has gotten quite high traffic (14K views by now) -- so I hope this will benefit your project as well.
Keep me posted on the new documentation, I'll be happy to augment the blog!

**Comment by vankichi** [comment]
Hi, @DmitryKey 

Thanks for updating diagram!

> Also, for your information this blog has gotten quite high traffic (14K views by now) -- so I hope this will benefit your project as well.

Wow! It's very exciting !
When you have any question, please contact to us anytime :)

BTW, were you able to join the slack ?

**Comment by DmitryKey** [comment]
I've tried to access Slack here: https://vald-community.slack.com/ssb/redirect

by clicking the Vald Slack button on main page https://vald.vdaas.org/
still it says, that my email "doesn’t have an account on this workspace."

Do you have a registration link? Or some other way to get in.
