### ISSUE TITLE
Return more explicit logs

### ISSUE THREAD

**Issue by vankichi** [vdaas/vald#1542]
### Is your feature request related to a problem? Please describe.:

I got the feedback. (see below)

> I have a problem with the lb-gateway.
> I tested inserting a few hundred vectors but when I try to retrieve one of the vector I inserted, I receive an error:
> status = StatusCode.NOT_FOUND
> details = "error search result length is 0"
> but if I try to connect to the agent directly instead of connecting to the gateway, everything works accordingly with the exact same request and I receive back the id of the correct vector with the expected distance of 0.
> Did I miss something? I am using the default example configuration. With agent.ngt.dimension=1024

It is because of the timeout of the search config.
However, the user cannot expect the reason immediately why this error happens.

### Describe the solution you'd like:

When the search phase finishes due to timeout, the error log would be not `NOT_FOUND`.
https://grpc.github.io/grpc/core/md_doc_statuscodes.html

### Describe alternatives you've considered:

I thought it would be better to add new error status and description.
- timeout
    - length = 0: code: `DEADLINE_EXCEEDED`, description: Search deadline exceeded, result = 0
    - 0 < length < `num`: `DEADLINE_EXCEEDED`, description: Search deadline exceeded, result = <length>

**Comment by kpango** [comment]
@hlts2 is working on it

**Comment by hlts2** [comment]
And in other feedback, there was a request to include a parameter for the required minimum number of search results in the search configuration value.
Therefore, another patterns will be added to the above timeout pattern.

The following is that.
- if the search time out and search results length is less than the required minimum number, return Deadline exceeded grpc status and search results is not enough error.
- If the search results length is less than the required minimum number, return not found grpc status, and search results are not enough error.

PR: https://github.com/vdaas/vald/pull/1546
