### ISSUE TITLE
Documentation on metadata insertion and egress filter

### ISSUE THREAD

**Issue by zstatmanweil** [vdaas/vald#1656]
### Is your feature request related to a problem? Please describe.:

I am trying to understand how to include metadata in the indexing process and then how to use the egress filter on a search. The documentation seems to indicate this is possible (which is awesome!) but it isn't clear to me how to incorporate it and I don't see it referenced in the python SDK, for example. This announcement also makes me think perhaps the metadata feature is deprecated? https://vdaas-vald.medium.com/announcement-some-unnecessary-components-will-be-deprecated-at-the-end-of-july-2021-9616ecfaa12b

### Describe the solution you'd like:

Documentation to clarify how to index metadata with the vectors. 

### Describe alternatives you've considered:

None.

Thank you!

**Comment by vankichi** [comment]
Hi @zstatmanweil !

Thanks for having an interest Vald!

Yes! You can use metadata with vectors in the indexing or any processes.
To achieve it, it requires you to implement your own ingress filter component and egress filter component and deploy it.
Each component should satisfy the Vald filter gateway's API interface.
(Ref: https://github.com/vdaas/vald/blob/master/apis/proto/v1/vald/filter.proto )

The example steps when you'd like to try inserting vectors with category labels are:
1. Send the insert request w/vector and label to Vald Ingress.
2. Vald Ingress passes the request to the Vald filter gateway, then it passes to your ingress filter component.
3. Your ingress filter returns the new vector which your model converts using the vector and the label.
4. Vald LB gateway gets the new vector and tries to insert Vald Agent.

> but it isn't clear to me how to incorporate it and I don't see it referenced in the python SDK, for example.

We're sorry about we provide the document about it.
Recently we published the [`vald-onnx-ingress-filter`](https://github.com/vdaas/vald-onnx-ingress-filter) as the official ingress filter component!
And the blog post is [here](https://medium.com/itnext/vald-released-the-new-vald-official-ingress-filter-vald-onnx-ingress-filter-b807e147188b) 
I wish they help you.

> This announcement also makes me think perhaps the metadata feature is deprecated? https://vdaas-
vald.medium.com/announcement-some-unnecessary-components-will-be-deprecated-at-the-end-of-july-2021-9616ecfaa12b

It is about Vald don't manage metadata used internally (such as uuid, id, pod's IP address, etc.)
So I suppose it does not relate to your issue.

Does that answer your question?
Please feel free to ask if you have any questions :)
Thanks :smile_cat:

**Comment by zstatmanweil** [comment]
Hi @vankichi , than you so much! That helps and I will dig into those resources.
