### ISSUE TITLE
K8s namespace

### ISSUE THREAD

**Issue by rinx** [vdaas/vald#264]
Should we use "vald" as K8s default namespaces?

**Comment by rinx** [comment]
As a result of our discussion, we're going to use "vald" as K8s default namespace.
I'll make PRs for it.

**Comment by kpango** [comment]
@rinx how's the progress of this issue?

**Comment by rinx** [comment]
we can close this PR if #248 is successfully merged.
https://github.com/vdaas/vald/pull/248/files#diff-ae388a6b10399d23e937151492085e3eR36

**Comment by kpango** [comment]
I made PR #291 and #248 was closed due to some problem,
please track #291
