### ISSUE TITLE
[Impl] SwissMap wrapper library for large scale data

### ISSUE THREAD

**Issue by vankichi** [vdaas/vald#2659]
### Is your feature request related to a problem? Please describe.:

Increasing the number of indexes in Vald can significantly increase Agent memory requirements, leading to higher infrastructure costs when handling large-scale data.
To optimize resource usage and maintain performance, we've enabled SwissMap.

### Describe the solution you'd like:

Introducing [SwissMap](https://github.com/dolthub/swiss)

### Describe alternatives you've considered:

- Implement a wrapper to use SwissMap with Vald
- Prepare options for using SwissMap (including Helm)
- Run performance tests and output the differences

**Comment by kpango** [comment]
Go 1.24 will resolve this issue.
