### ISSUE TITLE
Package document should contains in doc.go instead of the source code file

### ISSUE THREAD

**Issue by kevindiu** [vdaas/vald#315]
All of the package document contains in the source code file, instead of separated `doc.go` file, which affect the readability of the source code.
Each package should contains a `doc.go` file to describe the package.

Also some package doc is missing, like https://github.com/vdaas/vald/tree/master/internal.

**Comment by kpango** [comment]
I agree, please do that as a SET tasks!

**Comment by vankichi** [comment]
@kevindiu 
we decided to stack your proposal to the task and will get started working with creating/refactoring tests. Maybe, It will take much time. thank you for your proposal.
