### ISSUE TITLE
[proposal] Add more custom metrics for monitoring

### ISSUE THREAD

**Issue by rinx** [vdaas/vald#343]
## What is this proposal

All of the components in Vald have a functionality to export their metrics to Prometheus or other external monitoring system. (#131)
In this proposal, i'm going to discuss what metrics are needed for each components and how to implement them.

## metrics considered to be added (including already implemented)

:seedling: ... just an idea. need to be discussed
:leaves: ... can be split into smaller metrics. need to be discussed

### Commons
- [X] gRPC server metrics (latency, receive bytes, send bytes) using ocgrpc interceptor
- [X] memory metrics (heap, stack, sys, etc...)
- [X] goroutine count
- [X] GC count
- [X] CGO call count
- [ ] gRPC connection rebalance cumulative count :seedling:
- [ ] gRPC connected server count :seedling:
    - maybe `gRPCClient.clientCount` in internal/net/grpc/client.go
- [ ] received request cumulative count :seedling:
- [X] completed request cumulative count :seedling: (achieved by ocgrpc)

### Agent
- [X] NGT indices
- [X] NGT uncommitted indices
- [X] NGT insert/delete vcache
- [X] indexing flag
- [ ] indexing time total
- [X] completed indexing process cumulative count #389 
- [ ] received/completed search query request cumulative count :seedling:
- [ ] received/completed insert request cumulative count :seedling:
- [ ] received/completed update request cumulative count :seedling:
- [ ] received/completed delete request cumulative count :seedling:

#### Sidecar
- [ ] backup file size bytes
- [ ] completed backup cumulative count
- [ ] failed backup cumulative count
- [ ] time required to upload file (cumulative?)

### Gateway
- [ ] received/completed search query request cumulative count :seedling:
- [ ] received/completed insert request cumulative count :seedling:
- [ ] received/completed update request cumulative count :seedling:
- [ ] received/completed delete request cumulative count :seedling:

### Discoverer
- [ ] reconcile cumulative count :seedling:

#### Cassandra
- [x] completed query cumulative count
- [x] query latency

#### MySQL
- [x] completed query cumulative count :leaves:
- [x] query latency

### Compressor
- [X] requested registerer jobs cumulative count
- [X] completed registerer jobs cumulative count
- [X] registerer jobs count in queue
- [X] requested compressor jobs cumulative count
- [X] completed compressor jobs cumulative count
- [X] compressor jobs count in queue

### Index Manager
- [ ] UUID count
- [ ] uncommitted UUID count
- [ ] indexing flag

#### Cassandra
- [x] completed query cumulative count :leaves:
- [x] query latency

#### Redis
- [x] completed query cumulative count :leaves:
- [x] query latency

**Comment by rinx** [comment]
Cassandra query metrics can be implemented using gocql's functionality.
https://godoc.org/github.com/gocql/gocql#QueryObserver

**Comment by kpango** [comment]
It seems interesting.
also, I recommend to add observe interface to internal gRPC clients and TCP dialer

**Comment by kpango** [comment]
discoverer & gateway discovers ips from DNS. It would be better to observe tcp, udp & dns discovery rate.

**Comment by kpango** [comment]
I think it's better to watch backoff rate.

**Comment by rinx** [comment]
how about to add custom metrics like these?

>  tcp, udp & dns discovery rate.

- [ ] TCP discovery count
- [ ] UDP discovery count
- [ ] DNS discovery count

> backoff rate

- [ ] `internal/backoff/Backoff.Do` call count
- [ ] backoff attempts count

i think backoff metrics should be tagged by the caller function name. there are two types of method to fetch the caller name, the first is using `runtime.Caller` and `runtime.FuncForPC`, the second is passing `name` variable to `backoff` struct. which is better?

**Comment by kpango** [comment]
metrics looks good

I think we should pass the name for each Backoff.Do

**Comment by kpango** [comment]
Fortunately we're now planning to refactor backoff.Do function https://github.com/vdaas/vald/projects/3#card-42651099

**Comment by rinx** [comment]
Okay. we'll refactor internal/backoff and try to implement backoff metrics at the same time.

**Comment by rinx** [comment]
:memo: For MySQL metrics, dbr's TracingEventReceiver may be useful.
https://github.com/gocraft/dbr/blob/master/event.go#L17

For Redis metrics, go-redis's Hook may be useful.
https://github.com/go-redis/redis/blob/0ddc3abd36b0/redis.go#L22
