### ISSUE TITLE
Fix cycle import of `internal/errors` pacakge

### ISSUE THREAD

**Issue by hlts2** [vdaas/vald#351]
### Describe the bug:

We implement the test code based on the code automatically generated from the template. However, when I execute the `go test` command, the error occurs in` internal / errors`. The details of the error are cyclic imports. 

### To Reproduce:

I think it's because the template uses `errors.Errorf` statically. Therefore, in case of `errors` in the same package, I want to put an implementation that removes the `errors` prefix in the template. It also fixed existing errors.

### Expected behavior:

we expect that no occurs cyclic imports in the `internal/errors`.
and It also fixed existing errors.

### Environment:

- Golang Version: 1.13.5
- Docker Version: 19.03.5
- Kubernetes Version: 1.16.3
- NGT Version: 1.8.4

**Comment by vankichi** [comment]
Thank you for your report.
I stand with you and also want to fix this problem.
Could you please do below:
  - fix our template
  - fix existing test file which occurs cyclically import.
And then, please create a PR.

**Comment by vankichi** [comment]
This issue has been fixed by #359 .
Thank you a great job @kpango 😉
