### ISSUE TITLE
Accessing empty slice with no boundary checking causing error

### ISSUE THREAD

**Issue by kevindiu** [vdaas/vald#413]
### Describe the bug:
As @kpango reported, there are many missing boundary check on the slice. For example
https://github.com/vdaas/vald/blob/master/internal/core/ngt/ngt.go#L284

We may need to check the `vec[0]` is exists or not first.

One of the solution may be the following
```go

if len(vec) == 0 {
// handle
}

ret := C.ngt_search_index_as_float(
	n.index,
	(*C.float)(&vec[0]),
         .....
```

But in some case we do not need to do the boundary check, for example:
https://github.com/vdaas/vald/blob/master/internal/info/info.go#L170

### Environment:

- Golang Version: 1.13.5
- Docker Version: 19.03.5
- Kubernetes Version: 1.16.3
- NGT Version: 1.8.4

**Comment by kpango** [comment]
I think you cannot receive ok bool variable from slice

**Comment by kevindiu** [comment]
modified the description👀

**Comment by kevindiu** [comment]
I have scanned all the codes and couldn't find any missing boundary check in Vald. Maybe we can close this issue?

**Comment by kpango** [comment]
Thank you
