### ISSUE TITLE
pkg/agent/core/ngt/service/New blocks startup process of agent-ngt

### ISSUE THREAD

**Issue by rinx** [vdaas/vald#503]
### Describe the bug:

with invalid NGT backup files, pkg/agent/core/ngt/service/New blocks startup process of agent-ngt.

### To Reproduce:

put invalid backup files in `index_path` and `enable_in_memory_mode=false`.

### Expected behavior:

Maybe there are two options to fallback the application. :thinking:
- restart pod and retry to load
- start daemon without backup data.

### Environment:

- Go Version: 1.14.3
- Docker Version: 19.03.8
- Kubernetes Version: 1.18.2
- NGT Version: 1.11.5

**Comment by kpango** [comment]
Thank you for your feedback.
I think restart pod and download again looks good.
If we start daemon without backup data, S3 back up data will be overwritten, it makes problem for data consistency

**Comment by rinx** [comment]
resolved in #503
