### ISSUE TITLE
[Proposal] Improve singleflight pacakge

### ISSUE THREAD

**Issue by hlts2** [vdaas/vald#577]
### Is your feature request related to a problem? Please describe.:

The current implementation uses `sync.Mutex` and `map` to cache objects.
Removing the lock logic will improve performance.

### Describe the solution you'd like:

Since locks and unlocks occur frequently, replacing them with `sync.Map` can be made lock-free, which is considered to speed up the process.

### Describe alternatives you've considered:

Change from `sync.Mutex` and `map` to `sync.Map` to cache object.

**Comment by vankichi** [comment]
close

**Comment by vankichi** [comment]
colse
