### ISSUE TITLE
Default value is used when options failed without notifying user

### ISSUE THREAD

**Issue by kevindiu** [vdaas/vald#585]
### Is your feature request related to a problem? Please describe.:

When the option return error, currently the implementation will use the default value and continue the execution. 
But the problem is that the users do not know the default value is used because theres is no error message is printed when error occurred. 

For example:
https://github.com/vdaas/vald/blob/master/internal/servers/option.go#L58

### Describe the solution you'd like:

1. Print out the error and terminate the program.
    Users may need to understand all the parameters and set it correctly. 
    We provide helm chart with default values and users may not touch it if they don't understand the parameter.
2. Print out the error only
    Log the error and notify users that the default value is used. User may not see the log and the default value is used without any intention.

**Comment by rinx** [comment]
I think so too.
The solution 1 is preferred. I also think all the `Option` functions should return error like this.

```go
type Option func(*something) error
```

**Comment by kpango** [comment]
I think 2 looks better, because vald has a lot of parameters, and all Forcing the parameters to be user-controlled makes them harder to deploy.
However, I know there is a default variable in Helm Chart that's one of the ways to deploys the vald, not a vald.

**Comment by kevindiu** [comment]
After some discussion, we decide to return error in `Option`, and log or return the error from the caller side

**Comment by kpango** [comment]
As we already implemented option validation for each setting.
Users can now see the invalid option log and start up process using default value, which is plan 1.

So I'll close this issue.
